# 应用服务 WEB 访问端口
server:
  port: 8888
# 应用名称
spring:
  application:
    name: consumer

# dubbo 协议
dubbo:
  registry:
    address: zookeeper://localhost:2181
  # Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
  # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
  cloud:
    subscribed-services: consumer
  protocol:
    id: dubbo
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    # dubbo 服务扫描基准包
  scan:
    base-packages: com.example.demo
  consumer:
    threads: 1000
